# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15ee3397ce6c497e4b5fc5cc358c489f7d037d177bbe0666efedaf3599b90e49116218550bfa8f9cd39e900b776e2e88444845efcaf36c445e901c57a1cd3c18

test:
  secret_key_base: c8ef1a3ec8b1cb4cb630938dd4219ce409dd5e319bfa9c71d98782588fe04ad6fb2433cf858714e4049a03798a6ca2572c1f60e3b9b6ad5a0a358d330757136a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
